/* =====================================================================
   CardData
   Owns: immutable card definitions for completed Python's Quest decks.
   Stays out of: mutable card instances and effect execution.
   ===================================================================== */

import {
    CARD_TYPES,
    CHARACTER_IDS,
    EFFECT_IDS,
    TARGET_MODES,
} from "./Constants.js";
import { get_character_definition } from "./CharacterData.js";

function symbols(attack, defense, healing, draw, play_again) {
    return Object.freeze({ attack, defense, healing, draw, play_again });
}

function card_definition({
    id,
    character_id,
    name,
    copies,
    type,
    card_symbols,
    target_mode,
    effect_id,
    rules_text,
    flavor_text,
    skill_id = null,
}) {
    const skill = skill_id === null ? null : get_character_definition(character_id).abilities.find(ability => ability.id === skill_id);
    if (skill === undefined) throw new Error(`Unknown card skill: ${skill_id}`);
    return Object.freeze({
        id,
        character_id,
        name,
        copies,
        type,
        symbols: card_symbols,
        target_mode,
        effect_id,
        rules_text,
        flavor_text,
        skill,
    });
}

const CARD_DEFINITIONS = Object.freeze([
    card_definition({
        id: "grandpa_8_bit_blast",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "8-Bit Blast",
        copies: 4,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Deal 2 damage.",
        flavor_text: "256 shades of gray? That's 255 more than I need!",
    }),
    card_definition({
        id: "grandpa_back_in_my_day",
        skill_id: "monochrome_lecture",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Back In My Day",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 1, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.BACK_IN_MY_DAY,
        rules_text: "Target opponent's next attack deals 2 less damage, minimum 1. Draw 1 card.",
        flavor_text: "We didn't have these fancy 'combos' back then!",
    }),
    card_definition({
        id: "grandpa_boring_story",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Boring Story",
        copies: 3,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.BORING_STORY,
        rules_text: "Target opponent makes a DC 12 save. On failure, they discard 2 cards.",
        flavor_text: "It all started in 1982, when I purchased my first computer...",
    }),
    card_definition({
        id: "grandpa_crt_screen_flicker",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "CRT Screen Flicker",
        copies: 2,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 3, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.CRT_SCREEN_FLICKER,
        rules_text: "3 shields. When this shield breaks, deal 1 damage to the attacker.",
        flavor_text: "The static electricity will get you.",
    }),
    card_definition({
        id: "grandpa_dot_matrix_missile",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Dot Matrix Missile",
        copies: 3,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(3, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Deal 3 damage.",
        flavor_text: "Printed in real-time, delivered in dot-matrix quality.",
    }),
    card_definition({
        id: "grandpa_floppy_disk_of_power",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Floppy Disk of Power",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 3, 1),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.FLOPPY_DISK_OF_POWER,
        rules_text: "Draw 3 cards. Each opponent discards 1 card. Play Again.",
        flavor_text: "5.25 inches of pure storage capacity!",
    }),
    card_definition({
        id: "grandpa_grayscale_bomb",
        skill_id: "screen_burn_in",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Grayscale Bomb",
        copies: 2,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 0, 0),
        target_mode: TARGET_MODES.ALL_OPPONENTS,
        effect_id: EFFECT_IDS.GRAYSCALE_BOMB,
        rules_text: "Deal 2 damage to all opponents.",
        flavor_text: "Everything looks the same when it's gray anyway.",
    }),
    card_definition({
        id: "grandpa_loading_please_wait",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Loading... Please Wait",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.LOADING_PLEASE_WAIT,
        rules_text: "Target opponent draws 1 card on their next turn, then that turn ends.",
        flavor_text: "This will only take 15-20 minutes.",
    }),
    card_definition({
        id: "grandpa_memory_leak",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Memory Leak",
        copies: 2,
        type: CARD_TYPES.DRAW,
        card_symbols: symbols(0, 0, 0, 3, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Draw 3 cards.",
        flavor_text: "Wait, where did I put that spell? It was just here...",
    }),
    card_definition({
        id: "grandpa_monochrome_shield",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Monochrome Shield",
        copies: 2,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 4, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.MONOCHROME_SHIELD,
        rules_text: "4 shields. Dice-based attacks cannot destroy this shield.",
        flavor_text: "Randomness? Bah! Give me consistent grayscale!",
    }),
    card_definition({
        id: "grandpa_phosphor_burn",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Phosphor Burn",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.PHOSPHOR_BURN,
        rules_text: "Until your next turn, target opponent takes 1 damage whenever they play a card.",
        flavor_text: "That's what you get for leaving the same image on screen too long.",
    }),
    card_definition({
        id: "grandpa_refresh_rate",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Refresh Rate",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 2),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Play Again twice.",
        flavor_text: "60 Hz? Back in my day we had 30 Hz and we were GRATEFUL!",
    }),
    card_definition({
        id: "grandpa_screen_saver",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "Screen Saver",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 4, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.SCREEN_SAVER,
        rules_text: "4 shields. When this shield breaks, return it to your hand.",
        flavor_text: "Bouncing logo activates after 15 minutes of inactivity.",
    }),
    card_definition({
        id: "grandpa_the_olden_days",
        character_id: CHARACTER_IDS.GRANDPA,
        name: "The Olden Days",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.THE_OLDEN_DAYS,
        rules_text: "All players discard their hands. Each opponent draws 3 cards. You draw 5 cards.",
        flavor_text: "Let me tell you how we used to do things...",
    }),

    card_definition({
        id: "malric_aggressive_positioning",
        skill_id: "threat_generation",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Aggressive Positioning",
        copies: 3,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 1, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.AGGRESSIVE_POSITIONING,
        rules_text: "Gain 1 shield.",
        flavor_text: "Over here! No, over HERE!",
    }),
    card_definition({
        id: "malric_block_this",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Block This!",
        copies: 2,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 2, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.BLOCK_THIS,
        rules_text: "2 shields. When this shield breaks, deal 2 damage to the attacker.",
        flavor_text: "Shield bash on cooldown = improvised weapon.",
    }),
    card_definition({
        id: "malric_cooldown_ready",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Cooldown Ready!",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.COOLDOWN_READY,
        rules_text: "Return a Defense card from your discard pile to your hand.",
        flavor_text: "Fifteen second cooldown is up! Let's go again!",
    }),
    card_definition({
        id: "malric_defensive_stance",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Defensive Stance",
        copies: 3,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 3, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "3 shields.",
        flavor_text: "This is my default position.",
    }),
    card_definition({
        id: "malric_face_tank",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Face Tank",
        copies: 2,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 4, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.FACE_TANK,
        rules_text: "4 shields. When this shield breaks, heal 3 HP.",
        flavor_text: "Thanks for the health potion! Wait, that was YOUR damage?",
    }),
    card_definition({
        id: "malric_ignore_pain",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Ignore Pain",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.IGNORE_PAIN,
        rules_text: "The next attack targeting you deals 3 less damage, minimum 1.",
        flavor_text: "I didn't feel that. Try harder.",
    }),
    card_definition({
        id: "malric_inspiring_presence",
        skill_id: "second_wind",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Inspiring Presence",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 4, 2, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.INSPIRING_PRESENCE,
        rules_text: "Heal 4 HP. Draw 2 cards.",
        flavor_text: "Don't worry team, I've got this! What team? There is no team.",
    }),
    card_definition({
        id: "malric_looking_for_group",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Looking for Group",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.LOOKING_FOR_GROUP,
        rules_text: "Every opponent draws 1 card. You draw 2 cards.",
        flavor_text: "LFG: Need DPS, Healer, and someone to explain why I'm solo tanking.",
    }),
    card_definition({
        id: "malric_mocking_blow",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Mocking Blow",
        copies: 3,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.MOCKING_BLOW,
        rules_text: "Deal 2 damage. Target opponent must attack you on their next turn if able.",
        flavor_text: "Your mother was a hamster and your father smelt of elderberries!",
    }),
    card_definition({
        id: "malric_shield_bash",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Shield Bash",
        copies: 2,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 0, 1),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.SHIELD_BASH,
        rules_text: "Deal 2 damage, plus 1 if you have a Defense card in play. Play Again.",
        flavor_text: "My shield is also a weapon. Efficient!",
    }),
    card_definition({
        id: "malric_shield_wall",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Shield Wall",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 6, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.SHIELD_WALL,
        rules_text: "6 shields. Attacks dealing 3 or less damage cannot destroy this shield.",
        flavor_text: "DEFENSIVE COOLDOWN ACTIVATED!",
    }),
    card_definition({
        id: "malric_stand_your_ground",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Stand Your Ground",
        copies: 2,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 4, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.STAND_YOUR_GROUND,
        rules_text: "4 shields. You cannot be forced to discard cards while this shield is in play.",
        flavor_text: "I'M NOT MOVING!",
    }),
    card_definition({
        id: "malric_tank_specs",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Tank Specs",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 2, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.TANK_SPECS,
        rules_text: "Draw 2 cards. Until your next turn, Defense cards you play have 1 additional shield.",
        flavor_text: "Let me check my talent tree... yep, still specced for facetanking.",
    }),
    card_definition({
        id: "malric_vengeance",
        character_id: CHARACTER_IDS.MALRIC,
        name: "Vengeance",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 0, 1),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.VENGEANCE,
        rules_text: "Until your next turn, whenever you take damage, deal 1 damage to the attacker. Play Again.",
        flavor_text: "You're going to regret hitting the tank.",
    }),

    card_definition({
        id: "patchadin_all_paladin_raid",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "All Paladin Raid",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.ALL_PALADIN_RAID,
        rules_text: "Summon three Raid Paladins with 2 HP each. At the start of your turn, each attacks for 1 or heals you for 1.",
        flavor_text: "It's not broken, we're just really well organized!",
    }),
    card_definition({
        id: "patchadin_blessing_of_kings",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Blessing of Kings",
        copies: 1,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.BLESSING_OF_KINGS,
        rules_text: "Until your next turn, your attacks deal 2 additional damage and Defense cards you play gain 2 shields.",
        flavor_text: "Increased duration. Increased power. Decreased cooldown. You're welcome.",
    }),
    card_definition({
        id: "patchadin_bubble_hearth",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Bubble Hearth",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 5, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.BUBBLE_HEARTH,
        rules_text: "5 shields. This shield cannot be destroyed. At the end of your next turn, discard it and set your HP to 10.",
        flavor_text: "The most honorable PvP strategy known to the realm.",
    }),
    card_definition({
        id: "patchadin_crusader_strike",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Crusader Strike",
        copies: 4,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Deal 2 damage.",
        flavor_text: "The most reliable ability since 2007. They've never nerfed it. Yet.",
    }),
    card_definition({
        id: "patchadin_divine_shield",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Divine Shield",
        copies: 2,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 4, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.DIVINE_SHIELD,
        rules_text: "4 shields. When this shield breaks, heal 1 HP.",
        flavor_text: "Eight second immunity in PvP. Balanced? Definitely.",
    }),
    card_definition({
        id: "patchadin_divine_storm",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Divine Storm",
        copies: 2,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 0, 1),
        target_mode: TARGET_MODES.ALL_OPPONENTS,
        effect_id: EFFECT_IDS.DIVINE_STORM,
        rules_text: "Deal 2 damage to all opponents. Play Again.",
        flavor_text: "Why hit one when you can hit everyone?",
    }),
    card_definition({
        id: "patchadin_flash_of_light",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Flash of Light",
        copies: 2,
        type: CARD_TYPES.HEALING,
        card_symbols: symbols(0, 0, 3, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Heal 3 HP.",
        flavor_text: "Faster cast time. Cheaper cost. More healing. We see no issues here.",
    }),
    card_definition({
        id: "patchadin_hammer_of_wrath",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Hammer of Wrath",
        copies: 3,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(3, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Deal 3 damage.",
        flavor_text: "Patch 4.0: Now deals 50% more damage because reasons.",
    }),
    card_definition({
        id: "patchadin_hand_of_protection",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Hand of Protection",
        copies: 1,
        type: CARD_TYPES.DEFENSE,
        card_symbols: symbols(0, 3, 0, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.HAND_OF_PROTECTION,
        rules_text: "3 shields. Attacks dealing 3 or less damage cannot destroy this shield.",
        flavor_text: "Also known as Hand of Frustration by rogues everywhere.",
    }),
    card_definition({
        id: "patchadin_judgment",
        skill_id: "can_do_everything",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Judgment",
        copies: 2,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(2, 0, 0, 1, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Deal 2 damage. Draw 1 card.",
        flavor_text: "Cast from 30 yards away because melee is for peasants.",
    }),
    card_definition({
        id: "patchadin_lay_on_hands",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Lay on Hands",
        copies: 1,
        type: CARD_TYPES.HEALING,
        card_symbols: symbols(0, 0, 5, 0, 0),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.LAY_ON_HANDS,
        rules_text: "Heal 5 HP, then roll d6 and heal that much additional HP.",
        flavor_text: "Fully heal yourself instantly with no downside. This is fine.",
    }),
    card_definition({
        id: "patchadin_love_me_or_hate_me",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Love Me or Hate Me",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.LOVE_ME_OR_HATE_ME,
        rules_text: "Each opponent chooses Love to heal you 2 HP, or Hate to take 2 damage. Draw 1 card per Hate choice.",
        flavor_text: "Yes, we know we're overpowered. Deal with it.",
    }),
    card_definition({
        id: "patchadin_nerf_incoming",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Nerf Incoming",
        copies: 1,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(0, 0, 0, 0, 0),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.NERF_INCOMING,
        rules_text: "Target opponent's next attack deals 3 less damage, minimum 1. At the start of their next turn, they take 1 damage.",
        flavor_text: "Don't worry, it'll be reverted in the next patch.",
    }),
    card_definition({
        id: "patchadin_blatant_favoritism",
        skill_id: "developers_favorite",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Blatant Favoritism",
        copies: 2,
        type: CARD_TYPES.UTILITY,
        card_symbols: symbols(2, 1, 1, 0, 1),
        target_mode: TARGET_MODES.OPPONENT,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Deal 2 damage. Gain 1 shield. Heal 1 HP. Play Again.",
        flavor_text: "Because obviously, the devs ALL play Paladins!",
    }),
    card_definition({
        id: "patchadin_divine_intervention",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Divine Intervention",
        copies: 1,
        type: CARD_TYPES.MIGHTY_POWER,
        card_symbols: symbols(0, 0, 0, 0, 1),
        target_mode: TARGET_MODES.SELF,
        effect_id: EFFECT_IDS.DIVINE_INTERVENTION,
        rules_text: "Sacrifice all your Defense cards in play. Fully heal to your maximum HP. Play Again.",
        flavor_text: "Removed in an old expansion, but we never forgot.",
    }),
    card_definition({
        id: "patchadin_wake_of_ashes",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Wake of Ashes",
        copies: 1,
        type: CARD_TYPES.ATTACK,
        card_symbols: symbols(1, 0, 0, 0, 0),
        target_mode: TARGET_MODES.ALL_OPPONENTS,
        effect_id: EFFECT_IDS.WAKE_OF_ASHES,
        rules_text: "Deal 1 damage to all opponents. Choose one opponent: cancel their next Play Again action.",
        flavor_text: "We needed an AoE stun. For reasons.",
    }),
    card_definition({
        id: "patchadin_patch_notes",
        character_id: CHARACTER_IDS.PATCHADIN,
        name: "Patch Notes",
        copies: 2,
        type: CARD_TYPES.DRAW,
        card_symbols: symbols(0, 0, 0, 3, 0),
        target_mode: TARGET_MODES.NONE,
        effect_id: EFFECT_IDS.STANDARD,
        rules_text: "Draw 3 cards.",
        flavor_text: "We've updated Paladins again. Check the forums for salt.",
    }),
]);

const CARD_DEFINITION_BY_ID = new Map(CARD_DEFINITIONS.map((definition) => [definition.id, definition]));

export function get_card_definition(definition_id) {
    if (!CARD_DEFINITION_BY_ID.has(definition_id)) {
        throw new Error(`Unknown card definition id: ${definition_id}`);
    }

    return CARD_DEFINITION_BY_ID.get(definition_id);
}

export function get_card_definitions_for_character(character_id) {
    const definitions = CARD_DEFINITIONS.filter((definition) => definition.character_id === character_id);
    if (definitions.length === 0) {
        throw new Error(`No cards found for character id: ${character_id}`);
    }

    return definitions;
}

export function get_all_card_definitions() {
    return CARD_DEFINITIONS;
}
